name: Actions

on:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
  push:
    branches:
      - master
jobs:
  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Generate README.md
  #       uses: teoxoy/profile-readme-stats@v3
  #       with:
  #         token: ${{ secrets.USER_TOKEN }}
  #     - name: Update README.md
  #       run: |
  #         if [[ "$(git status --porcelain)" != "" ]]; then
  #           git config user.name github-actions[bot]
  #           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
  #           git add .
  #           git commit -m "chore: update README"
  #           git push
  #         fi
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: tuanductran
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_timezone: Asia/Ho_Chi_Minh
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
