name: Lint

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun lint

      - name: Lint Markdown
        run: bun run lint:md

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun test
