name: Prettier content MD

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Prettier check
        run: npx prettier --check "**/*.md"
      - name: Prettier format
        run: npx prettier --write "**/*.md"
