name: Prettier content MD

on:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
  push:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Install dependencies
        run: pnpm install
      - name: Prettier check and format
        run: npx prettier --check "**/*.md" && npx prettier --write "**/*.md"
